### ISSUE TITLE
MY WEBSITES

### ISSUE THREAD

**Issue by 331332** [adambotfd/dashboard-maker#51]
### Name

BusCheck

### Icon

data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAFwAXAMBIgACEQEDEQH/xAAcAAADAQEBAAMAAAAAAAAAAAAFBgcEAwIAAQj/xAA+EAACAQIEAwYEAQoFBQAAAAABAgMEEQAFEiEGMUEHEyJRYXEUgZGh8BUjMmKiscHC0dIzQnKCkhYkUrLD/8QAGQEAAwEBAQAAAAAAAAAAAAAAAQIDAAQF/8QAJxEAAgIBAwMCBwAAAAAAAAAAAAECEQMSITETQVEiYQQyUnGhsfD/2gAMAwEAAhEDEQA/ALGxsN9hbmcK2bcd5RlzmOBmrpRse4I0L7udvpfH12gCWphpMuhZ/wA+xLoradY5BT89/kcImb5PU5ehVMsd1AI1qpkA97XsPfD/AHJynp2W7Nlb2n5zOxFBRUtOp/R1Xkb+AwObjvi1jf4lB6CmAGFmpkVqqWGncBRt4SARpPljXRKywr3khbfot7Hrc+xUge+Mnje1fsF5fq/CGqi494nQg1CU08Y3ZdAVyB5b2vikQZpJDl8NbmAhWnlVWE8bgLZv0dj53GIzF/iLq5A3xR6gGXgTh0Mdu6iJBHO0ZwJQV2isMjaqSv8AvYcKeohqV1QSq4/VOO2nE3V2gCNTO0LBgLpy5+XLBmn4lq6XQKhRUKWC3GxF8bcNRfDG7Tj6wOoM/oK06VlEcnVH2OCY3Fxax9cFMVxaPOPmPVhj5gi0LGZHv+Jt+UKqvsQjN/8ARceatkWnmeRgkYQ3ZzYDbzOJ1xzxW1NxHmcENJM/cVBVnWseJW8CrayEHoBz6eWEvN+JJMzTumyqhi0keJY2kc+hZyTgN7E9Dcil8Mw5PUcKUH5SFFK5EgUyKC4GtiOXiG2BvFEWR0QposrmczzOkZSLVKioebcuY2tvc/Q4n9BmOYyzLHC5QltHhiRdrj09BjxXflRWgkmlmJltbVJyHT2wtj6PDHapoarLxStNHO0dTujywdyNgL8zy354oUqMOzzI59u7hgiaRidlBS1/a5GIPKKlmU1lQ8oA8BeRmsegF/xtj9K8CrfgnI1YbGgiuD/pGC3sGKEOaT80TGwbZSCDccxjjXVBSmkkvqMVpLDrpOr+GKBmOR5BVPIjU1PBOxtrQGMlrX3KkX23wBfhymklangzR4p2Nu7qYCVPlZrD95w0ZJjuEuUAw2pWUlLCRrC9+uCGXZnXUZbuqltP/g/iHLHxuE83oY1UwCpVQAXp3F9gBfS1j09ccIYFjl7utWSCTw2EyFCRvcWbn03xW4tElrXA0UXE6MAKyApvbvI/EL/g4NR19I63E6fM2OFKnshmVIvAx1b9Li33tjXGmqKNmaPxKCLi+Juuw6fkifEFYv8A1Dm1TI3hmqpiCN+cht9sDafNKSNZSEmaVnNnU2tYbdfbG6DLKatpZKqerrFkPibSqhATvzI5eZvjE9HSxR65oS0em+pqt7HfmAE3v0F8SlUthoS0u0aqLPoywD0rlDqY3e3md9vb8HGbNc6lqJIhHBGgPjfxdTe49By2wSynK8oqe+FTEEKx6hpmcgc7jxEAnlyGM81RR01U9NSUFExW15Kmkvv5bNhFCK7FHmnLlgozmpXS7ItyB4Rq2vvYX588fofgivqYaHLqOqloYqJMti7kGQCUsNjcE8regsRbETdnny5oI4aGOWZo9Ahpo4VUNIoF3AuPU35YJVEVRWvTALTGaJHh0yt4QA1yVa46sd7kHbFFTdEbLpX0U01Q0iRq0RG4V9ztz/h8gceZmrYZy8Stfu1DaVvc7W/ecQ2jlzOmMiUkVRG8G8jUtfIluuwA/ccM2XcQZ2kMTwZ1WFWQNaTTLzHIlgcaONJtod5nSTRUqWtqJJ443CEk7i1rC1/rcY31VNFVQmKdFdD0YXxMKbjzPYyuv4aoA3OuAg/VSP3Y3xdpjwqprsrRQTbUlSF/9wB98FxYutXsFszyVKNtSxER38MkRKH5jlf5YFGlmSyx1M4Qcg0SsR89sEaTtCybMYWEtNUopFnB7uQD/g5wPnzfJhJemzPTEd1WZZY2HyK7++ITjkj8p3YcmCe2VKyV0DiJZIBrVEdDIR6XK/Ll9MZc1MlVl9MEJ16A5PPrYbemNNNRwVFR/wBzTxytpCussYJibkV9CCPqPTBJcipoqlainjjjYKApja1je/z6YbTvZ53uKX5PqqaOWXvZhJFYyhbh41N9z1Ava59ceBq+LlDSd6SgOpR+lfr87YoFTBEmXSa01Npa91F99yAdweZ5+vnhErHhgqg0Co9mjbuyDZlWxsQOd72OHaRSKbC0LrTO5kspgpyCDsSVS5H3P0wxdoLNQVdGhqe6K5fTqoVd1OlQb+hthWoUmz7PKOhp6OKD42cxiKI2EaMSX0r0VV1fT2wydtqFeLbJffL4SFA6B2/p9sa6QKFifOZwJTTsqPPcBiL2A2+tscoKopMnxM9R3I1LpifSACSBz22t64zStDMrTaFiQXEUSnqbAW+QJPt64Zsn7PM9zrLYK+jam7ipBaIvJY8yP3g4R2w6aBtLxBLRwMsUYnk1HT3rE6QL9b9Dp++NNFxR8XpGbxpCiNq76nvysQBp3PO2C57H+J3C62oyRfcyc+X9MYM87OM84cympzOtNKYI9IOiS7C5t5euGuSFpA8580LhqBVV9wXmAZShNwbbWNgOZxkq6yuq6mScyAarG1Oz92PCOW+2OnCNFXZnxDSUeWGAVbxl4++JCkBNxcb8uWH6j7PuMKdHs2VP3jlye8YbkD+mJyeSXAaSPrivhXNvyhLnHDE0chqD3k9FKwAdjzZGO1z1B674WZc3zrL/AA5rwtmKMpsWWNgp9jpIP1wQyrtGlpI7VWXwSEeHTBI0Y58wpBHLyPpgse0rLnCP8LXQyDpFKCPnuBjp0WP0cngXvy/VGGMU2Q19Q8gs0Uasx5dQFxyy/hPijOSmnJocuS5LT5hYGxtYd3a+1j06+1mI9omX9KfNWHVXmWx/aP49hjye1COniEdHlDBVGxlqr/y7/XA6YViy9kNnBnCGV8II9Q8/xOYyp+cqpAAQg3IRR+iu1zzJ6nyVu22mE1blOa0pDx1VIY0cbg6TrX6hz9MB6jtEzaWUtRx01OxfUe7jYtuADYte21vLHLMKiaoympeeYyvLoMsj7kkHY3Pv9CRywzxtxbXYtD4SbjKTfAoCN9CCwDaxtflc4sPDPFFPw12XZPUz0UlfUrJMsUEVtXhdtTAnlYHpvvbEm8I3uCduvqP6YoHD9HSVPA9G1WJZZYnkjgSnYa4jJO15NJ5gWU+uki2OeN2cxYMgzalz7J6TNaB2anqYw635jzB9Qbg+2AfajEZ+As4RtrIpB58mU3wJ7FJGHDeYUZsFo8zniVRyUGzWH/I4I9qFfBFwrXUD6mmq4iiqv+UX/SPkMPTfAUm9kRngqZcl4vocxAaTuFlQR7AG8bAb+5GHOtzvMq2oaolrJlL8ljkZFUeQCnl73PrhGhmhpc1jqJXpoQri6mW4Xa3IknBZuIcsqSXhzB5FG2paUEftb9cUwelerk7PhHjjFuXICrclmEshpKhKiOxK6oCjE+W+w979ccKPKsySaKWaipHRWBMckzDUPI2xU5uFqRl8NTVJv/lKf24WM04ahExT4+vIuR/iqP5cLb8nL1ZeQLWulLTmY5BlUmhfEgqHufkQPthPgzAySqjJFEp5yPqIUefXDzNwTQSJresr2PrIh/lwPm4Oy9DtUVZ92X+3GtmWSS7i/NXoiaY61JP1ViZV/HyxspeJYzTNSVyOYZBpZ4Fu6gEG4BIB+2CMXB9A7AGeq59GX+3Dfk3ZlkE0Xe1D1sv6plAH7Kg4OuS7jrPkpqxAbOcggBEVDmNUDvaoqkjAP+xQflqw0cFcZKI/g4KdYkRm7mkiLSFixvza7E3tY723HUYfMu4S4fy1g1LlVOHHJ3Bdvqb4NRxpGLRxon+lQMIRI9luVdoeieDLGrMtpKidpmHfLTklupt4uQA+WNcfZXnWYy9/nOco0htqY652P+5iMWKgp0qJtDkgX6Y6VGinm7tI0P6z+I/fb7YxiaZd2RZLEw+Imraxuqhgg+ii/wB8GV7M+GlFjlCg+TVsqn6d5huaaQ3UudPkNh9MeL4Jj//Z

### Demo

Pls use /help for Detail Information!

/bc for a one-time bus arrival time check. For example:
/bc bus-stop:Ang Mo Kio Stn bus-service:268
or 
/bc bus-stop:02089 bus-service:77

If you want a panel that you can refresh do /bc-panel (will send to dms). For example:
/bc-panel bus-service:77 bus-stop-code:02089 title: fav mrt station

### ID

1056880835111948348

### Support

https://discord.gg/fNfYkpQcj2

### Description

BusCheck arrival time for Singapore Public Buses. (SBS, SMRT, GAS, TTS)

### INSTRUCTIONS
Wait 10s for a comment on this issue and follow the instructions provided

**Comment by adambotfd** [comment]
Your bots website will be live shortly! You can view it at https://disforge.vercel.app/BusCheck.html
